### ISSUE TITLE
Add ENS reverse resolution

### ISSUE THREAD

**Issue by kristoferlund** [kristoferlund/ic-wall#2]
"looks great! needs ENS reverse resolution so instead of seeing 0x addresses you could see their ENS name instead"

https://twitter.com/BrantlyMillegan/status/1409967450335199243

**Comment by DreamXzxy** [comment]
https://github.com/kristoferlund/ic-wall/pull/3

**Comment by kristoferlund** [comment]
Looks good @DreamXzxy, thanks! 🙏 ✨

 I'm on vacation but will have a closer look and merge in two weeks.

**Comment by kristoferlund** [comment]
@DreamXzxy I broke your PR by upgrading the app, sorry 😉. I had to make the switch from Next.js to CRA as that platform made no sense for this project. Do you have time to make a revisit and fix the PR?

**Comment by DreamXzxy** [comment]
> @DreamXzxy I broke your PR by upgrading the app, sorry 😉. I had to make the switch from Next.js to CRA as that platform made no sense for this project. Do you have time to make a revisit and fix the PR?

Sure.

**Comment by DreamXzxy** [comment]
@kristoferlund I made a new PR https://github.com/kristoferlund/ic-wall/pull/5
